# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Configuration for request-info - https://github.com/behaviorbot/request-info
# Configuration for update-docs - https://github.com/behaviorbot/update-docs

updateDocsComment: >
  Thanks for opening this pull request! I would appreciate it if you would update some of our documentation based on your changes.

updateDocsTargetFiles:
  - README

requestInfoReplyComment:
  - We would appreciate it if you could provide us with more info about this issue/pr!
  - Tell me more !
  - Ah no! young blade! That was a trifle short!

requestInfoLabelToAdd: needs-more-info

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the issue template!
  ![GIF](https://media.giphy.com/media/vQqeT3AYg8S5O/giphy.gif)

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines.
  ![GIF](https://media.giphy.com/media/ebFG4jcnC1Ny8/giphy.gif)

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! We are proud of you! 

# It is recommend to include as many gifs and emojis as possible