// Code generated by go generate; DO NOT EDIT.
// This file was generated at
// 2022-09-19 01:37:11.6433279 +0800 +08 m=+0.006297701
package goo

type Bool bool

func FromBool(n bool) Bool {
	return Bool(n)
}

// ToBool converts instance to builtin bool
func (n Bool) ToBool() bool {
	return bool(n)
}
