// Code generated by go generate; DO NOT EDIT.
// This file was generated at
// 2022-09-18 23:08:45.3757558 +0800 +08 m=+0.050232801
package goo

type Bool bool

func FromBool(n bool) Bool {
	return Bool(n)
}

// ToBool converts instance to builtin bool
func (n Bool) ToBool() bool {
	return bool(n)
}
