// Code generated by go generate; DO NOT EDIT.
// This file was generated at
// 2022-09-19 03:03:33.8231474 +0800 +08 m=+0.007318901
package goo

type Bool bool

// FromBool converts builtin type to Goo's bool
func FromBool(n bool) Bool {
	return Bool(n)
}

// ToBool converts instance to builtin bool
func (n Bool) ToBool() bool {
	return bool(n)
}
