// Code generated by go generate; DO NOT EDIT.
// This file was generated at
// 2022-09-19 01:37:13.2585619 +0800 +08 m=+0.006468201
package goo

type Complex128 complex128
type Complex64 complex64

func FromComplex128(n complex128) Complex128 {
	return Complex128(n)
}

// ToComplex128 converts instance to builtin complex128
func (n Complex128) ToComplex128() complex128 {
	return complex128(n)
}

func FromComplex64(n complex64) Complex64 {
	return Complex64(n)
}

// ToComplex64 converts instance to builtin complex64
func (n Complex64) ToComplex64() complex64 {
	return complex64(n)
}
