// Code generated by go generate; DO NOT EDIT.
package goo

type Rune rune

func FromRune(n rune) Rune {
	return Rune(n)
}

// ToInt32 converts instance to builtin int32
func (n Rune) ToRune() rune {
	return rune(n)
}
