// Code generated by go generate; DO NOT EDIT.
// This file was generated at
// 2022-09-18 22:15:17.6514799 +0800 +08 m=+0.004816701
package goo


type String string

func FromString(n string) String {
	return String(n)
}

// ToString converts instance to builtin string
func (n String) ToString() string {
	return string(n)
}
