version: 2.1

orbs:
  codecov: codecov/codecov@3.2.3
  go: circleci/go@1.7.1
jobs:
  build:
    executor:
      name: go/default
      tag: '1.19.1'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: false
          race: true
          coverprofile: coverage.out
          verbose: true
      - run:
          command: bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
                   --force-coverage-parser go -r <coverage report file name>
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build