version: 2.1

orbs:
  codecov: codecov/codecov@3.2.3
  go: circleci/go@1.7.1
jobs:
  build:
    executor:
      name: go/default
      tag: '1.19.1'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Code Climate before-build
          command: ./cc-test-reporter before-build
      - go/test:
          covermode: atomic
          failfast: false
          race: true
          coverprofile: coverage.out
          verbose: true
      - run:
          name: Code Climate after-build
          command: ./cc-test-reporter after-build --coverage-input-type cover --exit-code $?
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build