version: 2.1

orbs:
  codecov: codecov/codecov@3.2.3
  go: circleci/go@1.7.1
  coverage-reporter: codacy/coverage-reporter@13.10.14
jobs:
  build:
    executor:
      name: go/default
      tag: '1.19.1'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: false
          race: true
          coverprofile: coverage.out
          verbose: true
      - codecov/upload
      - coverage-reporter/send_report:
          coverage-reports: 'coverage.out'
          project-token: $CODACY_PROJECT_TOKEN

workflow:
  version: 2.1
  build-test:
    jobs:
      - build