version: 2.1

orbs:
  codecov: codecov/codecov@4.2.0
  go: circleci/go@1.9.0
jobs:
  build:
    executor:
      name: go/default
      tag: '1.19.1'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: false
          race: true
          coverprofile: coverage.out
          verbose: true
      - run:
          name: Codacy Test Coverage Upload
          command: bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
                   --force-coverage-parser go -r coverage.out
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build